### ISSUE TITLE
Separate Discovery/Expose

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-security#14]
In scripting API, there is discussion about whether Things should be Exposed but not Discoverable (and vice versa?).   Should coordinate discussion here with that discussion, and also in Security TF and document, discuss use cases/rationale for making Exposing/Consuming and Discoverable/Hidden being separate functions.

**Comment by mmccool** [comment]
Exposing a thing means its interactions are available.   Discovery means its TD is available.
But... there can be multiple ways to do discovery, with different security/performance implications: 1. register with a directory 2. respond to a broadcast 3. respond to a special URL on the device with a TD 4. someone gave me the TD and the URL already

And... who has the right to get responses to discovery requests?   There is also a difference in the level of security for access to the TD vs rights to interact with the device.

=> Not possible to have something discoverable that is not exposed...
=> But reasonable to have something exposed but not discovered (and... in OCF, there are properties that accessible but are not discoverable)
=> We agree that exposed and discoverable are different; are going to have different levels of access control
=> TD may be known, it doesn't mean you have rights to access the device
=> may be privacy issues from "free" discovery (anyone can discover...)

**Comment by mmccool** [comment]
This can be resolved as follows:
1. We don't cover discovery explicitly in our current charter so this is technically out of scope for a detailed security analysis.   If we don't specify the discovery mechanism we can't say anything about its security.
2. If there was a service supporting discovery, and that service was described with a TD, that TD could specify the access rights and requirements for discovery
3. TDs alone specify the interaction rights, but say nothing about discovery, and this is fine, since that is the scope of the TD.
4. We already state the security properties that any TD discovery mechanism should have, eg. provide TDs only to "authorized users".    However, we are vague as to how that is accomplished: we state the goal, not the mechanism, which is intentionally undefined
5. My reading of what Zoltan was saying above is that is not really an issue for the Scripting API.  Or rather, access rights are handled "outside" of the Scripting API, e.g. when its security is configured externally.

**Comment by zolkis** [comment]
Actually in the Scripting API we have made the discovery API specified in its own section, with the purpose of eventually scoping it out, since discovery in fact is an application. However, defining an umbrella API makes sense for the same reason why Thing Description makes sense for describing various protocols: it provides a consistent and simple way to deal with various discovery mechanisms.

For security: since discovery is an application, its security is based on general underlying protocol (and provisioning) security, both of which are out of scope for WoT. In the end I agree we don't need to explicitly cover it in a normative way, but we could have an informative section about usual security and privacy challenges with discovery. It's a crucial exposed surface from security point of view.

At least we should say that provisioning for discovery and protocol security belong to the deployment and are out of scope for WoT. However, IMHO we should make a security assessment on information the TD can expose about discovery.
