### ISSUE TITLE
Make links to the WoT Terminology from the WoT Architecture document

### ISSUE THREAD

**Issue by ereshetova** [w3c/wot-security#44]
TODO: "WoT Interface" is a term for the network API of a Thing 
defined in the WoT architecture document. How do we refer to these,
 and can we link to their definitions?

@zolkis
Yes, we should link to the WoT Terminology, from the Architecture Document.
https://w3c.github.io/wot-architecture/#terminology
Currently it is in a markdown.

In fact, the WoT Interface is the (network) interface of the WoT Runtime or WoT Servient (although I prefer the former term). The Scripting API is a middle API to help implementing a WoT Runtime. The Protocol Bindings are also a way to implement a WoT Runtime.
I made a relevant comment in this issue:
w3c/wot-architecture#35

**Comment by mmccool** [comment]
Rather than linking to the entire terminology section, ideally we would like to link to individual terms, either manually or automatically.   I looked through the ReSpec documentation but couldn't find any obvious way to do this.   Let's leave this issue open while we poke the W3C people responsible for ReSpec to see if this is possible, and if so, how to do it.   I'm guessing there is at least some way to format a URL to pick up the term.

**Comment by mmccool** [comment]
Doesn't seem to possible to do interdoc-links.   Can just create a local list of terms we are using, and mark those as definitions.   Optionally, those definitions can link to the definition in wot-architecture.

**Comment by zolkis** [comment]
I agree, for now we should create local Terminology, then when the terms are moved to the Architecture spec, they need to be defined in an externally referenceable way.

**Comment by mmccool** [comment]
Done, a while ago.
