### ISSUE TITLE
Blockchains for WoT

### ISSUE THREAD

**Issue by ereshetova** [w3c/wot-security#52]
Take a look on opportunities from using blockchains for authentication in WoT

**Comment by mmccool** [comment]
Also perhaps Interledger for payments

**Comment by mmccool** [comment]
But... I think we should do other kinds of authorization first.   That said, I think Interledger would be a good place to start for "blockchain authorization" since not only are you authorizing an IoT service... you're paying for it!   There may however be other blockchain authorization services we should look at, e.g. using hyperledger directly rather than through interledger.

**Comment by mmccool** [comment]
I'm planning to do a prototype for this for the next plugfest.   There are some interesting related things in the NDSS DISS workshop.

**Comment by mmccool** [comment]
I don't think this is a high priority right now and unless and until there is a well-known standard we need to support this should probably be closed.
