### ISSUE TITLE
Require Not Exposing Immutable Hardware Identifiers?

### ISSUE THREAD

**Issue by jasonanovak** [w3c/wot-security#70]
The note states that unique object identifiers "[c]an be a highly sensitive asset due to privacy implications of tracking” which is a good observation and the recommendation is made to avoid exposing any immutable hardware identifiers”.

Given the privacy risk, is it possible to make it be a WoT requirement (rather than a recommendation) to not expose immutable hardware identifiers?

**Comment by mmccool** [comment]
Note that there are several use cases that do need unique identifiers.   The main issue is that these should not be *immutable* identifiers, i.e. it should be possible for the user to re-provision their device and change such identifiers.

The real question is whether we can "require" this.   Hardware provisioning is basically out of scope of the WoT specification (since we generally want to describe existing devices...), and we have no mechanism to validate compliance with such a policy.  The Security Considerations document is actually informative, not normative.

However... want to bring up this issue with the TD WG and see if is appropriate to put normative language in the TD specification.   Certainly not exposing immutable hardware identifiers should be a STRONG recommendation.

**Comment by mmccool** [comment]
Also a privacy risk... let's discuss it as noted here: https://github.com/w3c/wot-security/issues/72

**Comment by mmccool** [comment]
Then there is this:
https://en.wikipedia.org/wiki/Unique_Device_Identification
In other words, in some domains (medical) immutable identifiers are _required by law_.  The real question is therefore how they are **accessed**.   Probably such immutable identifiers should only be accessible over the network (if at all; need to look at regulations to see if it is required) by an entity with suitable (high) access rights.   The "id" field in the TD should *not* be the UDI.

**Comment by mmccool** [comment]
To resolve this, I think we need a PR to define "immutable" appropriately in the definition of id and hash it out with the group.
https://w3c.github.io/wot-thing-description/#thing

**Comment by mmccool** [comment]
This is now discussed in the security and privacy considerations of the TD.
