### ISSUE TITLE
Discussion of WoT Fingerprinting Risks

### ISSUE THREAD

**Issue by jasonanovak** [w3c/wot-security#72]
There should be a discussion of fingerprinting risks given that a WoT configuration (e.g. what devices are where) is likely unique and can uniquely identify a user.  Moreover, fact that two people who have the same WoT configuration are likely in the same physical location.

**Comment by mmccool** [comment]
See https://github.com/mmccool/ndss-wot-sec/blob/master/ndss-diss-008.pdf where this is one of several risks discussed.   In fact, there are much more direct ways to identify devices if the TD includes a UUID, which is in fact required for several use cases.  You can also infer things about people from certain combinations or number of devices (eg you can probably "fingerprint" married couples without children, for instance).

The real solution here is to control who has access to TDs, since they obviously may have privacy-sensitive data.  This boils down to access rights for the discovery service (eg the Thing Dictionary) as well as how TDs are packaged and delivered (encrypted, etc).   One complication here is that the Thing Dictionary is not in the scope of the charter so we can't technically say anything normative about it (in *this* round of standardization, anyway).

**Comment by mmccool** [comment]
Right now we don't have a separate privacy section in the document but mention various privacy risks in different places in the document.   It might be useful to create an explicit "privacy" section that can list in one place the privacy threats and risks (but this section can just refer/hyperlink to other sections of the document for details).

**Comment by mmccool** [comment]
A table defining several privacy risks is now part of the public editor's draft.   Please review.  We don't yet have a discussion of mitigations.

**Comment by mmccool** [comment]
Given no further feedback, we are going to consider the changes to the Security and Privacy Considerations document have addressed these issue.
